### ISSUE TITLE
TypeError: search() got an unexpected keyword argument 'num'

### ISSUE THREAD

**Issue by Xworld777** [Li0N77/L7#1]
TypeError: search() got an unexpected keyword argument 'num'

**Comment by Li0N77** [comment]
the module you installed not same using in my script
in terminal : 
pip uninstall googlesearch-python
or 
pip uninstall python-googlesearch

and run the script well download the module automatically
& tommorow i well publish a new version

**Comment by Li0N77** [comment]
now i update somethings in script to work perfect
